name: Build project

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .java-version

      - uses: gradle/actions/wrapper-validation@v5

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew projectCodestyle

      - run: ./gradlew assemble check  --scan

      - run: ./gradlew publishToMavenLocal

      - run: git diff --exit-code

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: plugin-reports
          path: "${{ github.workspace }}/**/build/reports"

  build-sample-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .java-version

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew assemble check verifyPaparazzi --scan
        working-directory: sample

      - uses: actions/upload-artifact@v4
        with:
          name: sample-app-apk
          path: sample/app/build/outputs/apk/release/*.apk

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: all-sample-app-reports
          path: sample/app/build/reports

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: paparazzi-failure
          path: sample/app/build/paparazzi
