name: Build project

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: gradle/actions/wrapper-validation@v3

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew projectCodestyle

      - run: ./gradlew assemble check  --scan

      - run: ./gradlew projectCoverage

      - run: ./gradlew publishToMavenLocal

      - run: git diff --exit-code

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "${{ github.workspace }}/**/build/reports/tests"

      - name: Upload jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: "${{ github.workspace }}/**/build/reports/jacoco"


      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: lint-results
          path: '${{ github.workspace }}/**/build/**/reports/lint-results-*.html'

  build-sample-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew assemble check verifyPaparazzi --scan
        working-directory: sample

      - uses: actions/upload-artifact@v4
        with:
          name: sample-app-apk
          path: sample/app/build/outputs/apk/release/*.apk

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: all-sample-app-reports
          path: sample/app/build/reports
